# This is should not be part of the final theme build

routes:

collections:
  /writes/:
    permalink: /writes/{slug}/
    template: tag
    filter: primary_tag:blog
    data: tag.blog
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
